### PR TITLE
Prevent concatenation from causing JS errors

### PR DESCRIPTION
**Pull request by JimmyRittenborg**
But this fixes it.

### CODE REVIEW

**Comment by AugustMiller** [comment]
Thanks, @JimmyRittenborg!

I'd noticed early-on that the Panel actually concatenates all the custom field dependencies _directly in-line_, but I hadn't yet encountered a situation where other JS was included without "proper" trailing semi-colons.

This is a great one-line improvement!

**Comment by AugustMiller** [comment]
Going to wait until I can test this out on a project before merging— probably tonight.

**Comment by AugustMiller** [comment]
Verified. Merging and closing.

**Comment by AugustMiller** [comment]
Thanks, @JimmyRittenborg! Glad to have you on board.

**Comment by JimmyRittenborg** [comment]
@AugustMiller you're welcome 👌🏻

**Pull request merged**
